#!/bin/sh

# Get Application Install Directory
if (cat /etc/palm/luna.conf | grep -i "/media/cryptofs/apps") ; then
	INSTDIR=/media/cryptofs/apps
else
	INSTDIR=/var
fi

#Update Database (call Java)
sh $INSTDIR/usr/palm/applications/org.webosinternals.messaging/MessagingPlugins.sh $INSTDIR InstallPlugin facebook

#Copy files to main source
cp -f $INSTDIR/usr/palm/applications/org.webosinternals.messagingfacebook/usr/lib/purple-2/libfacebook.so $INSTDIR/usr/palm/applications/org.webosinternals.messaging/usr/lib/purple-2/libfacebook.so
cp -f $INSTDIR/usr/palm/applications/org.webosinternals.messagingfacebook/usr/lib/purple-2/lifacebook.la $INSTDIR/usr/palm/applications/org.webosinternals.messaging/usr/lib/purple-2/libfacebook.la

exit 0