#!/bin/sh

# Get Application Install Directory
if (cat /etc/palm/luna.conf | grep -i "/media/cryptofs/apps") ; then
	INSTDIR=/media/cryptofs/apps
else
	INSTDIR=/var
fi

#Copy libraries (These can't be symbolic links as the Pre wont boot afterwards)
cp -f $INSTDIR/usr/palm/applications/org.webosinternals.messagingsysfiles/usr/lib/libpurple.so.0.6.2 /usr/lib/libpurple.so.0.6.2
rm -f /usr/lib/libpurple.so
rm -f /usr/lib/libpurple.so.0
ln -s /usr/lib/libpurple.so.0.6.2 /usr/lib/libpurple.so
ln -s /usr/lib/libpurple.so.0.6.2 /usr/lib/libpurple.so.0
cp -f $INSTDIR/usr/palm/applications/org.webosinternals.messagingsysfiles/usr/lib/libtasn1.so.3 /usr/lib/libtasn1.so.3
cp -f $INSTDIR/usr/palm/applications/org.webosinternals.messagingsysfiles/usr/lib/libgnutls.so.26 /usr/lib/libgnutls.so.26
cp -f $INSTDIR/usr/palm/applications/org.webosinternals.messagingsysfiles/usr/lib/libjson-glib-1.0.so.0 /usr/lib/libjson-glib-1.0.so.0

#Copy to /tmp first otherwise you get an endpoint not connected error
cp -f $INSTDIR/usr/palm/applications/org.webosinternals.messagingsysfiles/usr/lib/libglib-2.0.so.0.1400.4 /usr/lib/libglib-2.0.so.0.2000.4
rm -f /usr/lib/libglib-2.0.so.0
ln -s /usr/lib/libglib-2.0.so.0.2000.4 /usr/lib/libglib-2.0.so.0

#Remount Cryptofs (glib and crypt.so unmount this)
umount cryptofs
/usr/bin/mountcfs

exit 0
