#!/bin/sh

# Get Application Install Directory
if (cat /etc/palm/luna.conf | grep -i "/media/cryptofs/apps") ; then
	INSTDIR=/media/cryptofs/apps
else
	INSTDIR=/var
fi
             
#Cleanup Sym-Links and files
rm -f /usr/lib/libglib-2.0.so.0
ln -s /usr/lib/libglib-2.0.so.0.1400.4 /usr/lib/libglib-2.0.so.0
rm -f /usr/lib/libglib-2.0.so.0.2000.4
rm -f /usr/lib/libpurple.so
rm -f /usr/lib/libpurple.so.0
rm -f /usr/lib/libpurple.so.0.6.2
ln -s /usr/lib/libpurple.so.0.5.1 /usr/lib/libpurple.so
ln -s /usr/lib/libpurple.so.0.5.1 /usr/lib/libpurple.so.0
rm -f /usr/lib/libtasn1.so.3
rm -f /usr/lib/libgnutls.so.26

#Remount Cryptofs (glib and crypt.so unmount this)
umount cryptofs
/usr/bin/mountcfs

exit 0
