#!/bin/sh

#Get WebOS Version
/usr/bin/luna-send -n 1 palm://com.palm.preferences/systemProperties/Get {\"key\":\"com.palm.properties.version\"} 2>/var/tmp/webosver

#Unload Messaging Application
/usr/bin/luna-send palm://com.palm.applicationManager/close "{\"processId\":\"1010\"}" 

#Kill LibpurpleAdapterExt if it's running
kill `ps -ef | grep LibpurpleAdapterExt | grep -v grep | awk '{print $2}'` 

#Backup Files (only if they don't exist already)
if [ ! -f /var/luna/data/dbdata/PalmDatabase.db3.messback ]; then
	cp /var/luna/data/dbdata/PalmDatabase.db3 /var/luna/data/dbdata/PalmDatabase.db3.messback
fi
if [ ! -f /usr/palm/applications/com.palm.app.messaging/app/models/messaging-constants.js.messback ]; then
	cp /usr/palm/applications/com.palm.app.messaging/app/models/messaging-constants.js /usr/palm/applications/com.palm.app.messaging/app/models/messaging-constants.js.messback
fi
if [ ! -f /usr/palm/applications/com.palm.app.messaging/app/models/messaging-luna-service.js.messback ]; then
	cp /usr/palm/applications/com.palm.app.messaging/app/models/messaging-luna-service.js /usr/palm/applications/com.palm.app.messaging/app/models/messaging-luna-service.js.messback
fi
if [ ! -f /usr/palm/applications/com.palm.app.messaging/app/views/prefsSetupAccount/prefsSetupAccount-scene.html.messback ]; then
	cp /usr/palm/applications/com.palm.app.messaging/app/views/prefsSetupAccount/prefsSetupAccount-scene.html /usr/palm/applications/com.palm.app.messaging/app/views/prefsSetupAccount/prefsSetupAccount-scene.html.messback
fi
if [ ! -f /usr/palm/applications/com.palm.app.messaging/app/controllers/listview-assistant.js.messback ]; then
	cp /usr/palm/applications/com.palm.app.messaging/app/controllers/listview-assistant.js /usr/palm/applications/com.palm.app.messaging/app/controllers/listview-assistant.js.messback
fi
if [ ! -f /usr/palm/applications/com.palm.app.messaging/app/controllers/prefsAccountSummary-assistant.js.messback ]; then
	cp /usr/palm/applications/com.palm.app.messaging/app/controllers/prefsAccountSummary-assistant.js /usr/palm/applications/com.palm.app.messaging/app/controllers/prefsAccountSummary-assistant.js.messback
fi
if [ ! -f /usr/palm/applications/com.palm.app.messaging/app/controllers/prefsAccountTypeList-assistant.js.messback ]; then
	cp /usr/palm/applications/com.palm.app.messaging/app/controllers/prefsAccountTypeList-assistant.js /usr/palm/applications/com.palm.app.messaging/app/controllers/prefsAccountTypeList-assistant.js.messback
fi
if [ ! -f /usr/palm/applications/com.palm.app.messaging/app/controllers/prefsSetupAccount-assistant.js.messback ]; then
	cp /usr/palm/applications/com.palm.app.messaging/app/controllers/prefsSetupAccount-assistant.js /usr/palm/applications/com.palm.app.messaging/app/controllers/prefsSetupAccount-assistant.js.messback
fi
if [ ! -f /usr/palm/frameworks/mojo/submissions/200.18/stylesheets/global-widget-addressing.css.messback ]; then
	cp /usr/palm/frameworks/mojo/submissions/200.18/stylesheets/global-widget-addressing.css /usr/palm/frameworks/mojo/submissions/200.18/stylesheets/global-widget-addressing.css.messback
fi
if [ ! -f /usr/palm/frameworks/mojo/submissions/200.18/stylesheets/global-iconography.css.messback ]; then
	cp /usr/palm/frameworks/mojo/submissions/200.18/stylesheets/global-iconography.css /usr/palm/frameworks/mojo/submissions/200.18/stylesheets/global-iconography.css.messback
fi

#Backup Palm Libraries
if [ ! -f /usr/lib/libglib-2.0.so.0.1400.4.messback ]; then
	cp /usr/lib/libglib-2.0.so.0.1400.4 /usr/lib/libglib-2.0.so.0.1400.4.messback
fi
if [ ! -f /usr/lib/libjson-glib-1.0.so.0.messback ]; then
	cp /usr/lib/libjson-glib-1.0.so.0 /usr/lib/libjson-glib-1.0.so.0.messback
fi
if [ ! -f /usr/lib/libpurple.so.0.5.1.messback ]; then
	cp /usr/lib/libpurple.so.0.5.1 /usr/lib/libpurple.so.0.5.1.messback
fi
if [ ! -f /usr/lib/libgpg-error.so.0.3.0.messback ]; then
	cp /usr/lib/libgpg-error.so.0.3.0 /usr/lib/libgpg-error.so.0.3.0.messback
fi
if [ ! -f /usr/lib/libcjson.so.messback ]; then
	cp /usr/lib/libcjson.so /usr/lib/libcjson.so.messback
fi
if [ ! -f /usr/lib/libgcrypt.so.11.5.2.messback ]; then
	cp /usr/lib/libgcrypt.so.11.5.2 /usr/lib/libgcrypt.so.11.5.2.messback
fi
if [ ! -d /usr/lib/purple-2.messback ]; then
	cp /usr/lib/purple-2 /usr/lib/purple-2.messback -r
fi

#Copy Java Installer
cp /var/usr/palm/applications/org.webosinternals.messaging/usr/share/dbus-1/system-services/im.libpurpleext.greg.service /usr/share/dbus-1/system-services/

#Create sym links for java
ln -s /var/usr/lib/luna/java/org.webosinternals.messaging.jar /usr/lib/luna/java/org.webosinternals.messaging.jar 

#Patch messaging application
/var/usr/bin/patch -f /usr/palm/applications/com.palm.app.messaging/app/models/messaging-constants.js < /var/usr/palm/applications/org.webosinternals.messaging/messaging-constants.patch
/var/usr/bin/patch -f /usr/palm/frameworks/mojo/submissions/200.18/stylesheets/global-iconography.css < /var/usr/palm/applications/org.webosinternals.messaging/global-iconography.patch
/var/usr/bin/patch -f /usr/palm/frameworks/mojo/submissions/200.18/stylesheets/global-widget-addressing.css < /var/usr/palm/applications/org.webosinternals.messaging/global-widget-addressing.patch
/var/usr/bin/patch -f /usr/palm/applications/com.palm.app.messaging/app/models/messaging-luna-service.js < /var/usr/palm/applications/org.webosinternals.messaging/messaging-luna-service.patch
/var/usr/bin/patch -f /usr/palm/applications/com.palm.app.messaging/app/views/prefsSetupAccount/prefsSetupAccount-scene.html < /var/usr/palm/applications/org.webosinternals.messaging/prefsSetupAccount-scene.patch
/var/usr/bin/patch -f /usr/palm/applications/com.palm.app.messaging/app/controllers/listview-assistant.js < /var/usr/palm/applications/org.webosinternals.messaging/listview-assistant.patch
/var/usr/bin/patch -f /usr/palm/applications/com.palm.app.messaging/app/controllers/prefsAccountSummary-assistant.js < /var/usr/palm/applications/org.webosinternals.messaging/prefsAccountSummary-assistant.patch
/var/usr/bin/patch -f /usr/palm/applications/com.palm.app.messaging/app/controllers/prefsAccountTypeList-assistant.js < /var/usr/palm/applications/org.webosinternals.messaging/prefsAccountTypeList-assistant.patch
/var/usr/bin/patch -f /usr/palm/applications/com.palm.app.messaging/app/controllers/prefsSetupAccount-assistant.js < /var/usr/palm/applications/org.webosinternals.messaging/prefsSetupAccount-assistant.patch

#Update Database (call Java)
sh /var/usr/palm/applications/org.webosinternals.messaging/MessagingPlugins.sh InstallPlugin Live 
sh /var/usr/palm/applications/org.webosinternals.messaging/MessagingPlugins.sh InstallPlugin ICQ 
#sh /var/usr/palm/applications/org.webosinternals.messaging/MessagingPlugins.sh InstallPlugin Facebook
sh /var/usr/palm/applications/org.webosinternals.messaging/MessagingPlugins.sh InstallPlugin SIPE
sh /var/usr/palm/applications/org.webosinternals.messaging/MessagingPlugins.sh InstallPlugin Jabber
sh /var/usr/palm/applications/org.webosinternals.messaging/MessagingPlugins.sh InstallPlugin IRC
sh /var/usr/palm/applications/org.webosinternals.messaging/MessagingPlugins.sh InstallPlugin Sametime
sh /var/usr/palm/applications/org.webosinternals.messaging/MessagingPlugins.sh InstallPlugin Groupwise
sh /var/usr/palm/applications/org.webosinternals.messaging/MessagingPlugins.sh InstallPlugin Palm   #Should be last!

#Copy files for installation
cp /var/usr/palm/applications/org.webosinternals.messaging/usr/lib/purple-2/* /usr/lib/purple-2/
cp /var/usr/palm/applications/org.webosinternals.messaging/usr/lib/* /usr/lib/
cp /var/usr/palm/applications/org.webosinternals.messaging/usr/share/purple/ca-certs/* /usr/share/purple/ca-certs
cp /var/usr/palm/applications/org.webosinternals.messaging/usr/palm/applications/com.palm.app.messaging/images/transports/* /usr/palm/applications/com.palm.app.messaging/images/transports/
cp /var/usr/palm/applications/org.webosinternals.messaging/usr/palm/frameworks/mojo/submissions/200.18/images/accounts/* /usr/palm/frameworks/mojo/submissions/200.18/images/accounts/
cp /var/usr/palm/applications/org.webosinternals.messaging/usr/palm/applications/com.palm.app.messaging/app/views/prefsSetupAccount/* /usr/palm/applications/com.palm.app.messaging/app/views/prefsSetupAccount/

#Install LibpurpleAdapterExt
cp /var/usr/palm/applications/org.webosinternals.messaging/usr/bin/LibpurpleAdapterExt /usr/bin/

#Create sym links for ICQ Plugin
ln -s /usr/lib/purple-2/liboscar.so.0.0.0 /usr/lib/purple-2/liboscar.so.0 

#Create sym links for Jabber
ln -s /usr/lib/purple-2/libjabber.so.0.0.0 /usr/lib/libjabber.so.0
ln -s /usr/lib/libgnutls.so.13.2.2 /usr/lib/libgnutls.so.26
ln -s /usr/lib/libtasn1.so.3.1.4 /usr/lib/libtasn1.so.3
ln -s /usr/lib/purple-2/liboscar.so.0 /usr/lib/liboscar.so.0
ln -s /usr/lib/libymsg.so.0.0.0 /usr/lib/libymsg.so.0

#Cleanup Sym-Links (even when I copy a file to backup sometimes the symlink follows the backup?!?!)
rm /usr/lib/libglib-2.0.so.0
ln -s /usr/lib/libglib-2.0.so.0.1400.4 /usr/lib/libglib-2.0.so.0
rm /usr/lib/libpurple.so
rm /usr/lib/libpurple.so.0
ln -s /usr/lib/libpurple.so.0.5.1 /usr/lib/libpurple.so
ln -s /usr/lib/libpurple.so.0.5.1 /usr/lib/libpurple.so.0
rm /usr/lib/libgpg-error.so
rm /usr/lib/libgpg-error.so.0
ln -s /usr/lib/libgpg-error.so.0.3.0 /usr/lib/libgpg-error.so
ln -s /usr/lib/libgpg-error.so.0.3.0 /usr/lib/libgpg-error.so.0
rm /usr/lib/libgcrypt.so.11
ln -s /usr/lib/libgcrypt.so.11.5.2 /usr/lib/libgcrypt.so.11

#Chmod LibPurpleAdapterExt and MessagingPlugins.sh
chmod 755 /usr/bin/LibpurpleAdapterExt
chmod 755 /var/usr/palm/applications/org.webosinternals.messaging/MessagingPlugins.sh

#Cleanup
rm /var/tmp/webosver

# Restart the service handler
/sbin/stop java-serviceboot
/sbin/start java-serviceboot

#Restart Luna (call Java)
sh /var/usr/palm/applications/org.webosinternals.messaging/MessagingPlugins.sh RestartLuna 

exit 0
