#!/bin/sh

# Get Application Install Directory
if (cat /etc/palm/luna.conf | grep -i "/media/cryptofs/apps") ; then
	INSTDIR=/media/cryptofs/apps
else
	INSTDIR=/var
fi

#Update Database (call Java)
sh $INSTDIR/usr/palm/applications/org.webosinternals.messaging/MessagingPlugins.sh $INSTDIR InstallPlugin Groupwise

#Copy files to main source
cp -f $INSTDIR/usr/palm/applications/org.webosinternals.messaginggroupwise/usr/lib/purple-2/libnovell.so $INSTDIR/usr/palm/applications/org.webosinternals.messaging/usr/lib/purple-2/libnovell.so
cp -f $INSTDIR/usr/palm/applications/org.webosinternals.messaginggroupwise/usr/lib/purple-2/libnovell.la $INSTDIR/usr/palm/applications/org.webosinternals.messaging/usr/lib/purple-2/libnovell.la

exit 0