#!/bin/sh

# Get Application Install Directory
if (cat /etc/palm/luna.conf | grep -i "/media/cryptofs/apps") ; then
	INSTDIR=/media/cryptofs/apps
else
	INSTDIR=/var
fi

#Update Database (call Java)
sh $INSTDIR/usr/palm/applications/org.webosinternals.messaging/MessagingPlugins.sh $INSTDIR InstallPlugin SIPE

#Copy files to main source
cp -f $INSTDIR/usr/palm/applications/org.webosinternals.messagingofficecommunicator/usr/lib/purple-2/libsipe.so $INSTDIR/usr/palm/applications/org.webosinternals.messaging/usr/lib/purple-2/libsipe.so
cp -f $INSTDIR/usr/palm/applications/org.webosinternals.messagingofficecommunicator/usr/lib/purple-2/libsipe.la $INSTDIR/usr/palm/applications/org.webosinternals.messaging/usr/lib/purple-2/libsipe.la

exit 0