#!/bin/sh

#Get WebOS Version
/usr/bin/luna-send -n 1 palm://com.palm.preferences/systemProperties/Get {\"key\":\"com.palm.properties.version\"} 2>/var/tmp/webosver

if (cat /var/tmp/webosver | grep -i 1.2); then
	WEBOSVER=1.2
fi
if (cat /var/tmp/webosver | grep -i 1.3); then
	WEBOSVER=1.3
fi

#Unload Messaging Application
/usr/bin/luna-send -n 1 "palm://com.palm.applicationManager/close" "{\"processId\":\"1010\"}"

#Kill LibpurpleAdapterExt if it's running
kill `ps -ef | grep LibpurpleAdapterExt | grep -v grep | awk '{print $2}'`

#Update Database (call Java)
sh /var/usr/palm/applications/org.webosinternals.messaging/MessagingPlugins.sh RemovePlugin Live
sh /var/usr/palm/applications/org.webosinternals.messaging/MessagingPlugins.sh RemovePlugin ICQ
#sh /var/usr/palm/applications/org.webosinternals.messaging/MessagingPlugins.sh RemovePlugin Facebook
sh /var/usr/palm/applications/org.webosinternals.messaging/MessagingPlugins.sh RemovePlugin SIPE
sh /var/usr/palm/applications/org.webosinternals.messaging/MessagingPlugins.sh RemovePlugin Jabber
sh /var/usr/palm/applications/org.webosinternals.messaging/MessagingPlugins.sh RemovePlugin IRC
sh /var/usr/palm/applications/org.webosinternals.messaging/MessagingPlugins.sh RemovePlugin Sametime
sh /var/usr/palm/applications/org.webosinternals.messaging/MessagingPlugins.sh RemovePlugin Groupwise
sh /var/usr/palm/applications/org.webosinternals.messaging/MessagingPlugins.sh RemovePlugin QQ
if (echo $WEBOSVER | grep -i 1.2); then
	sh /var/usr/palm/applications/org.webosinternals.messaging/MessagingPlugins.sh RemovePlugin Palm #Should be last!
fi

#Restore Files (Unpatch)
/var/usr/bin/patch -f /usr/palm/applications/com.palm.app.messaging/app/models/messaging-constants.js -R -d / < /var/usr/palm/applications/org.webosinternals.messaging/Patches/$WEBOSVER/messaging-constants.patch
/var/usr/bin/patch -f /usr/palm/applications/com.palm.app.messaging/app/models/messaging-luna-service.js -R -d / < /var/usr/palm/applications/org.webosinternals.messaging/Patches/$WEBOSVER/messaging-luna-service.patch
/var/usr/bin/patch -f /usr/palm/applications/com.palm.app.messaging/app/views/prefsSetupAccount/prefsSetupAccount-scene.html -R -d / < /var/usr/palm/applications/org.webosinternals.messaging/Patches/$WEBOSVER/prefsSetupAccount-scene.patch
/var/usr/bin/patch -f /usr/palm/applications/com.palm.app.messaging/app/controllers/prefsAccountTypeList-assistant.js -R -d / < /var/usr/palm/applications/org.webosinternals.messaging/Patches/$WEBOSVER/prefsAccountTypeList-assistant.patch
/var/usr/bin/patch -f /usr/palm/applications/com.palm.app.messaging/app/controllers/prefsSetupAccount-assistant.js -R -d / < /var/usr/palm/applications/org.webosinternals.messaging/Patches/$WEBOSVER/prefsSetupAccount-assistant.patch
/var/usr/bin/patch -f /usr/palm/applications/com.palm.app.messaging/app/controllers/compose-assistant.js -R -d / < /var/usr/palm/applications/org.webosinternals.messaging/Patches/$WEBOSVER/compose-assistant.patch
if (echo $WEBOSVER | grep -i 1.2); then
	/var/usr/bin/patch -f /usr/palm/frameworks/mojo/submissions/200.18/stylesheets/global-iconography.css -R -d / < /var/usr/palm/applications/org.webosinternals.messaging/Patches/$WEBOSVER/global-iconography.patch
	/var/usr/bin/patch -f /usr/palm/frameworks/mojo/submissions/200.18/stylesheets/global-widget-addressing.css -R -d / < /var/usr/palm/applications/org.webosinternals.messaging/Patches/$WEBOSVER/global-widget-addressing.patch
fi
if (echo $WEBOSVER | grep -i 1.3); then
	/var/usr/bin/patch -f /usr/palm/frameworks/mojo/submissions/200.47/stylesheets/global-iconography.css -R -d / < /var/usr/palm/applications/org.webosinternals.messaging/Patches/$WEBOSVER/global-iconography.patch
	/var/usr/bin/patch -f /usr/palm/frameworks/mojo/submissions/200.47/stylesheets/global-widget-addressing.css -R -d / < /var/usr/palm/applications/org.webosinternals.messaging/Patches/$WEBOSVER/global-widget-addressing.patch
fi

#Cleanup Patching Failures
rm /usr/palm/applications/com.palm.app.messaging/app/models/*.rej
rm /usr/palm/applications/com.palm.app.messaging/app/controllers/*.rej
rm /usr/palm/applications/com.palm.app.messaging/app/models/*.orig
rm /usr/palm/applications/com.palm.app.messaging/app/controllers/*.orig
if (echo $WEBOSVER | grep -i 1.2); then
	rm /usr/palm/frameworks/mojo/submissions/200.18/stylesheets/*.orig
	rm /usr/palm/frameworks/mojo/submissions/200.18/stylesheets/*.rej
fi
if (echo $WEBOSVER | grep -i 1.3); then
	rm /usr/palm/frameworks/mojo/submissions/200.47/stylesheets/*.orig
	rm /usr/palm/frameworks/mojo/submissions/200.47/stylesheets/*.rej
fi

#Restore Palm Libraries
if [ -f /usr/lib/libglib-2.0.so.0.1400.4.messback ]; then
	if [ -f /usr/lib/libglib-2.0.so.0.1400.4 ]; then
		rm /usr/lib/libglib-2.0.so.0.1400.4
		mv /usr/lib/libglib-2.0.so.0.1400.4.messback /usr/lib/libglib-2.0.so.0.1400.4
	fi
fi
if [ -f /usr/lib/libjson-glib-1.0.so.0.messback ]; then
	if [ -f /usr/lib/libjson-glib-1.0.so.0 ]; then
		rm /usr/lib/libjson-glib-1.0.so.0
		mv /usr/lib/libjson-glib-1.0.so.0.messback /usr/lib/libjson-glib-1.0.so.0
	fi
fi
if [ -f /usr/lib/libpurple.so.0.5.1.messback ]; then
	if [ -f /usr/lib/libpurple.so.0.5.1 ]; then
		rm /usr/lib/libpurple.so.0.5.1
		mv /usr/lib/libpurple.so.0.5.1.messback /usr/lib/libpurple.so.0.5.1
	fi
fi
if [ -d /usr/lib/purple-2.messback ]; then
	if [ -d /usr/lib/purple-2 ]; then
		rm /usr/lib/purple-2/ -r
		mv /usr/lib/purple-2.messback /usr/lib/purple-2
	fi
fi

#Remove installed files
rm -f /usr/palm/applications/com.palm.app.messaging/images/transports/facebook*.png
rm -f /usr/palm/applications/com.palm.app.messaging/images/transports/icq*.png
rm -f /usr/palm/applications/com.palm.app.messaging/images/transports/messenger*.png
rm -f /usr/palm/applications/com.palm.app.messaging/images/transports/irc*.png
rm -f /usr/palm/applications/com.palm.app.messaging/images/transports/jabber*.png
rm -f /usr/palm/applications/com.palm.app.messaging/images/transports/novell*.png
rm -f /usr/palm/applications/com.palm.app.messaging/images/transports/sametime*.png
rm -f /usr/palm/applications/com.palm.app.messaging/images/transports/sipe*.png
rm -f /usr/palm/applications/com.palm.app.messaging/images/transports/qq*.png
if (echo $WEBOSVER | grep -i 1.2); then
	rm -f /usr/palm/frameworks/mojo/submissions/200.18/images/accounts/icq*.png
	rm -f /usr/palm/frameworks/mojo/submissions/200.18/images/accounts/messenger*.png
	rm -f /usr/palm/frameworks/mojo/submissions/200.18/images/accounts/irc*.png
	rm -f /usr/palm/frameworks/mojo/submissions/200.18/images/accounts/jabber*.png
	rm -f /usr/palm/frameworks/mojo/submissions/200.18/images/accounts/novell*.png
	rm -f /usr/palm/frameworks/mojo/submissions/200.18/images/accounts/sametime*.png
	rm -f /usr/palm/frameworks/mojo/submissions/200.18/images/accounts/sipe*.png
	rm -f /usr/palm/frameworks/mojo/submissions/200.18/images/accounts/qq*.png
fi
if (echo $WEBOSVER | grep -i 1.3); then
	rm -f /usr/palm/frameworks/mojo/submissions/200.47/images/accounts/icq*.png
	rm -f /usr/palm/frameworks/mojo/submissions/200.47/images/accounts/messenger*.png
	rm -f /usr/palm/frameworks/mojo/submissions/200.47/images/accounts/irc*.png
	rm -f /usr/palm/frameworks/mojo/submissions/200.47/images/accounts/jabber*.png
	rm -f /usr/palm/frameworks/mojo/submissions/200.47/images/accounts/novell*.png
	rm -f /usr/palm/frameworks/mojo/submissions/200.47/images/accounts/sametime*.png
	rm -f /usr/palm/frameworks/mojo/submissions/200.47/images/accounts/sipe*.png
	rm -f /usr/palm/frameworks/mojo/submissions/200.47/images/accounts/qq*.png
fi
rm -f /usr/lib/libjson-glib-1.0.so.0

#Cleanup Sym-Links
rm /usr/lib/libglib-2.0.so.0
ln -s /usr/lib/libglib-2.0.so.0.1400.4 /usr/lib/libglib-2.0.so.0
rm /usr/lib/libpurple.so
rm /usr/lib/libpurple.so.0
ln -s /usr/lib/libpurple.so.0.5.1 /usr/lib/libpurple.so
ln -s /usr/lib/libpurple.so.0.5.1 /usr/lib/libpurple.so.0

#Restart Luna (call Java)
sh /var/usr/palm/applications/org.webosinternals.messaging/MessagingPlugins.sh RestartLuna

#Remove sym links, java file and install directory
rm -f /var/usr/lib/luna/java/org.webosinternals.messaging.jar
rm -f /usr/lib/luna/java/org.webosinternals.messaging.jar
rm -f /usr/palm/applications/org.webosinternals.messaging/ -r
rm -f /usr/lib/libjabber.so.0
rm -f /usr/lib/liboscar.so.0
rm -f /usr/lib/libymsg.so.0
rm -f /var/tmp/webosver

exit 0