#!/bin/sh

# Get Application Install Directory
if (cat /etc/palm/luna.conf | grep -i "/media/cryptofs/apps") ; then
	INSTDIR=/media/cryptofs/apps
else
	INSTDIR=/var
fi

#Get WebOS Version
/usr/bin/luna-send -n 1 palm://com.palm.preferences/systemProperties/Get {\"key\":\"com.palm.properties.version\" 2>/var/tmp/webosver

#Set Defaults
WEBOSVER=1.4
PATCH_LOG=/media/internal/webos-patches.log
SUBVER=`ls /usr/palm/frameworks/mojo/submissions -lrt | awk '/^d/ {f=$NF }; END{ print f }'`

if (cat /var/tmp/webosver | grep -i 1.4); then
	WEBOSVER=1.4
	if [ "$SUBVER" == "" ]; then
		SUBVER=330
	fi
fi
if (cat /var/tmp/webosver | grep -i 1.4.5); then
	WEBOSVER=1.4
	if [ "$SUBVER" == "" ]; then
		SUBVER=347
	fi
fi

# Check for Patch
if [ ! -f $INSTDIR/usr/bin/patch ]; then
	echo "" >> $PATCH_LOG
	echo "----------------------------------" >> $PATCH_LOG
	echo "$INSTDIR/usr/bin/patch not installed!" >> $PATCH_LOG
	echo "Please install GNU Patch from Preware first." >> $PATCH_LOG
	echo "----------------------------------" >> $PATCH_LOG
	exit 1
fi

CheckPatch() {
	if (!(echo $? | grep "0")); then
	{
		echo "" >> $PATCH_LOG
		echo "----------------------------------" >> $PATCH_LOG
		echo "CHECKING FAILED!" >> $PATCH_LOG
		echo "Patching of $1 will fail! Another patch must have modified this file. Fix this file and try again." >> $PATCH_LOG
		echo "----------------------------------" >> $PATCH_LOG
		exit 1
	}
	fi
}

PatchFailed() {
	if (!(echo $? | grep "0")); then
	{
		echo "" >> $PATCH_LOG
		echo "----------------------------------" >> $PATCH_LOG
		echo "Installation FAILED!" >> $PATCH_LOG
		echo "Patching of $1 failed! Remove messaging plugins \(patch\) and any other messaging patches and try again." >> $PATCH_LOG
		echo "----------------------------------" >> $PATCH_LOG
		exit 1
	}
	fi
}

#Unload Messaging Application
/usr/bin/luna-send palm://com.palm.applicationManager/close "{\"processId\":\"1010\"}" 

#Create patch log
if [ ! -e $PATCH_LOG ]
then
  touch $PATCH_LOG
  echo "******* Patch Log Created by postinst $(date) ************" >> $PATCH_LOG
fi

echo "" >> $PATCH_LOG
echo "------------------------------------------------------" >> $PATCH_LOG
echo "PATCH INSTALLATION $(date)" >> $PATCH_LOG
echo "------------------------------------------------------" >> $PATCH_LOG
echo "Messaging Plugins" >> $PATCH_LOG

#TEST - Patch messaging application
$INSTDIR/usr/bin/patch -N --dry-run /usr/palm/applications/com.palm.app.messaging/app/models/messaging-constants.js < $INSTDIR/usr/palm/applications/org.webosinternals.messaging/Patches/$WEBOSVER/messaging-constants.patch || CheckPatch messaging-constants >> $PATCH_LOG
if (grep  -i "isNumberValid" /usr/palm/applications/com.palm.app.messaging/app/models/messaging-luna-service.js) ; then
	$INSTDIR/usr/bin/patch -N --dry-run /usr/palm/applications/com.palm.app.messaging/app/models/messaging-luna-service.js < $INSTDIR/usr/palm/applications/org.webosinternals.messaging/Patches/$WEBOSVER/messaging-luna-service.smstonepatch || CheckPatch messaging-luna-service >> $PATCH_LOG
	$INSTDIR/usr/bin/patch -N --dry-run /usr/palm/applications/com.palm.app.messaging/app/controllers/listview-assistant.js < $INSTDIR/usr/palm/applications/org.webosinternals.messaging/Patches/$WEBOSVER/listview-assistant.smstonepatch || CheckPatch listview-assistant >> $PATCH_LOG
else
	$INSTDIR/usr/bin/patch -N --dry-run /usr/palm/applications/com.palm.app.messaging/app/models/messaging-luna-service.js < $INSTDIR/usr/palm/applications/org.webosinternals.messaging/Patches/$WEBOSVER/messaging-luna-service.patch || CheckPatch messaging-luna-service >> $PATCH_LOG
	$INSTDIR/usr/bin/patch -N --dry-run /usr/palm/applications/com.palm.app.messaging/app/controllers/listview-assistant.js < $INSTDIR/usr/palm/applications/org.webosinternals.messaging/Patches/$WEBOSVER/listview-assistant.patch || CheckPatch listview-assistant >> $PATCH_LOG
fi

if (grep  -i "pv_notification_repeat_interval_value" /usr/palm/applications/com.palm.app.messaging/app/views/prefsAccountSummary/prefsAccountSummary-scene.html) ; then
	$INSTDIR/usr/bin/patch -N --dry-run /usr/palm/applications/com.palm.app.messaging/app/views/prefsAccountSummary/prefsAccountSummary-scene.html < $INSTDIR/usr/palm/applications/org.webosinternals.messaging/Patches/$WEBOSVER/prefsAccountSummary-scene.repeatpatch || CheckPatch prefsAccountSummary-scene >> $PATCH_LOG
	$INSTDIR/usr/bin/patch -N --dry-run /usr/palm/applications/com.palm.app.messaging/app/controllers/prefsAccountSummary-assistant.js < $INSTDIR/usr/palm/applications/org.webosinternals.messaging/Patches/$WEBOSVER/prefsAccountSummary-assistant.repeatpatch || CheckPatch prefsAccountSummary-assistant >> $PATCH_LOG
else
	$INSTDIR/usr/bin/patch -N --dry-run /usr/palm/applications/com.palm.app.messaging/app/views/prefsAccountSummary/prefsAccountSummary-scene.html < $INSTDIR/usr/palm/applications/org.webosinternals.messaging/Patches/$WEBOSVER/prefsAccountSummary-scene.patch || CheckPatch prefsAccountSummary-scene >> $PATCH_LOG
	$INSTDIR/usr/bin/patch -N --dry-run /usr/palm/applications/com.palm.app.messaging/app/controllers/prefsAccountSummary-assistant.js < $INSTDIR/usr/palm/applications/org.webosinternals.messaging/Patches/$WEBOSVER/prefsAccountSummary-assistant.patch || CheckPatch prefsAccountSummary-assistant >> $PATCH_LOG
fi

if (grep  -i "enterSubmits: false" /usr/palm/applications/com.palm.app.messaging/app/controllers/compose-assistant.js) ; then
	$INSTDIR/usr/bin/patch -N --dry-run /usr/palm/applications/com.palm.app.messaging/app/controllers/compose-assistant.js < $INSTDIR/usr/palm/applications/org.webosinternals.messaging/Patches/$WEBOSVER/compose-assistant.enterpatch || CheckPatch compose-assistant >> $PATCH_LOG
else
	$INSTDIR/usr/bin/patch -N --dry-run /usr/palm/applications/com.palm.app.messaging/app/controllers/compose-assistant.js < $INSTDIR/usr/palm/applications/org.webosinternals.messaging/Patches/$WEBOSVER/compose-assistant.patch || CheckPatch compose-assistant >> $PATCH_LOG
fi

$INSTDIR/usr/bin/patch -N --dry-run /usr/palm/applications/com.palm.app.messaging/app/views/prefsSetupAccount/prefsSetupAccount-scene.html < $INSTDIR/usr/palm/applications/org.webosinternals.messaging/Patches/$WEBOSVER/prefsSetupAccount-scene.patch || CheckPatch prefsSetupAccount-scene >> $PATCH_LOG
$INSTDIR/usr/bin/patch -N --dry-run /usr/palm/applications/com.palm.app.messaging/app/controllers/prefsAccountTypeList-assistant.js < $INSTDIR/usr/palm/applications/org.webosinternals.messaging/Patches/$WEBOSVER/prefsAccountTypeList-assistant.patch || CheckPatch prefsAccountTypeList-assistant >> $PATCH_LOG
$INSTDIR/usr/bin/patch -N --dry-run /usr/palm/applications/com.palm.app.messaging/app/controllers/prefsSetupAccount-assistant.js < $INSTDIR/usr/palm/applications/org.webosinternals.messaging/Patches/$WEBOSVER/prefsSetupAccount-assistant.patch || CheckPatch prefsSetupAccount-assistant >> $PATCH_LOG
$INSTDIR/usr/bin/patch -N --dry-run /usr/palm/applications/com.palm.app.messaging/stylesheets/messaging.css < $INSTDIR/usr/palm/applications/org.webosinternals.messaging/Patches/$WEBOSVER/messaging.patch || CheckPatch messaging >> $PATCH_LOG
$INSTDIR/usr/bin/patch -N --dry-run /usr/palm/frameworks/mojo/submissions/$SUBVER/stylesheets/global-iconography.css < $INSTDIR/usr/palm/applications/org.webosinternals.messaging/Patches/$WEBOSVER/global-iconography.patch || CheckPatch global-iconography >> $PATCH_LOG
$INSTDIR/usr/bin/patch -N --dry-run /usr/palm/frameworks/mojo/submissions/$SUBVER/stylesheets/global-widget-addressing.css < $INSTDIR/usr/palm/applications/org.webosinternals.messaging/Patches/$WEBOSVER/global-widget-addressing.patch || CheckPatch global-widget-addressing >> $PATCH_LOG
$INSTDIR/usr/bin/patch -N --dry-run /usr/palm/applications/com.palm.app.messaging/app/views/prefsAccountSummary/accountsRow.html < $INSTDIR/usr/palm/applications/org.webosinternals.messaging/Patches/$WEBOSVER/accountsRow.patch || CheckPatch accountsRow >> $PATCH_LOG

#TEST - Patch Contacts Application
$INSTDIR/usr/bin/patch -N --dry-run /usr/palm/applications/com.palm.app.contacts/app/models/edit-rules.js < $INSTDIR/usr/palm/applications/org.webosinternals.messaging/Patches/$WEBOSVER/edit-rules.patch || CheckPatch edit-rules >> $PATCH_LOG
$INSTDIR/usr/bin/patch -N --dry-run /usr/palm/applications/com.palm.app.contacts/app/models/im-model.js < $INSTDIR/usr/palm/applications/org.webosinternals.messaging/Patches/$WEBOSVER/im-model.patch || CheckPatch im-model >> $PATCH_LOG

if [ -f /usr/palm/applications/com.palm.app.messaging/resources/de_de/views/prefsSetupAccount/prefsSetupAccount-scene.html ]; then
	#Other languages
	$INSTDIR/usr/bin/patch -N --dry-run /usr/palm/applications/com.palm.app.messaging/resources/de_de/views/prefsSetupAccount/prefsSetupAccount-scene.html < $INSTDIR/usr/palm/applications/org.webosinternals.messaging/Patches/$WEBOSVER/de_de_prefsSetupAccount-scene.patch || CheckPatch de_de_prefsSetupAccount-scene >> $PATCH_LOG
	$INSTDIR/usr/bin/patch -N --dry-run /usr/palm/applications/com.palm.app.messaging/resources/es_es/views/prefsSetupAccount/prefsSetupAccount-scene.html < $INSTDIR/usr/palm/applications/org.webosinternals.messaging/Patches/$WEBOSVER/es_es_prefsSetupAccount-scene.patch || CheckPatch es_es_prefsSetupAccount-scene >> $PATCH_LOG
	$INSTDIR/usr/bin/patch -N --dry-run /usr/palm/applications/com.palm.app.messaging/resources/es_us/views/prefsSetupAccount/prefsSetupAccount-scene.html < $INSTDIR/usr/palm/applications/org.webosinternals.messaging/Patches/$WEBOSVER/es_us_prefsSetupAccount-scene.patch || CheckPatch es_us_prefsSetupAccount-scene >> $PATCH_LOG
	$INSTDIR/usr/bin/patch -N --dry-run /usr/palm/applications/com.palm.app.messaging/resources/fr_ca/views/prefsSetupAccount/prefsSetupAccount-scene.html < $INSTDIR/usr/palm/applications/org.webosinternals.messaging/Patches/$WEBOSVER/fr_ca_prefsSetupAccount-scene.patch || CheckPatch fr_ca_prefsSetupAccount-scene >> $PATCH_LOG
	$INSTDIR/usr/bin/patch -N --dry-run /usr/palm/applications/com.palm.app.messaging/resources/fr_fr/views/prefsSetupAccount/prefsSetupAccount-scene.html < $INSTDIR/usr/palm/applications/org.webosinternals.messaging/Patches/$WEBOSVER/fr_fr_prefsSetupAccount-scene.patch || CheckPatch fr_fr_prefsSetupAccount-scene >> $PATCH_LOG
	$INSTDIR/usr/bin/patch -N --dry-run /usr/palm/applications/com.palm.app.messaging/resources/it_it/views/prefsSetupAccount/prefsSetupAccount-scene.html < $INSTDIR/usr/palm/applications/org.webosinternals.messaging/Patches/$WEBOSVER/it_it_prefsSetupAccount-scene.patch || CheckPatch it_it_prefsSetupAccount-scene >> $PATCH_LOG
fi

if [ -f /usr/palm/applications/com.palm.app.messaging/resources/de_de/views/prefsAccountSummary/prefsAccountSummary-scene.html ]; then
	#Other languages
	$INSTDIR/usr/bin/patch -N --dry-run /usr/palm/applications/com.palm.app.messaging/resources/de_de/views/prefsAccountSummary/prefsAccountSummary-scene.html < $INSTDIR/usr/palm/applications/org.webosinternals.messaging/Patches/$WEBOSVER/de_de_prefsAccountSummary-scene.patch || CheckPatch de_de_prefsAccountSummary-scene >> $PATCH_LOG
	$INSTDIR/usr/bin/patch -N --dry-run /usr/palm/applications/com.palm.app.messaging/resources/es_es/views/prefsAccountSummary/prefsAccountSummary-scene.html < $INSTDIR/usr/palm/applications/org.webosinternals.messaging/Patches/$WEBOSVER/es_es_prefsAccountSummary-scene.patch || CheckPatch es_es_prefsAccountSummary-scene >> $PATCH_LOG
	$INSTDIR/usr/bin/patch -N --dry-run /usr/palm/applications/com.palm.app.messaging/resources/es_us/views/prefsAccountSummary/prefsAccountSummary-scene.html < $INSTDIR/usr/palm/applications/org.webosinternals.messaging/Patches/$WEBOSVER/es_us_prefsAccountSummary-scene.patch || CheckPatch es_us_prefsAccountSummary-scene >> $PATCH_LOG
	$INSTDIR/usr/bin/patch -N --dry-run /usr/palm/applications/com.palm.app.messaging/resources/fr_ca/views/prefsAccountSummary/prefsAccountSummary-scene.html < $INSTDIR/usr/palm/applications/org.webosinternals.messaging/Patches/$WEBOSVER/fr_ca_prefsAccountSummary-scene.patch || CheckPatch fr_ca_prefsAccountSummary-scene >> $PATCH_LOG
	$INSTDIR/usr/bin/patch -N --dry-run /usr/palm/applications/com.palm.app.messaging/resources/fr_fr/views/prefsAccountSummary/prefsAccountSummary-scene.html < $INSTDIR/usr/palm/applications/org.webosinternals.messaging/Patches/$WEBOSVER/fr_fr_prefsAccountSummary-scene.patch || CheckPatch fr_fr_prefsAccountSummary-scene >> $PATCH_LOG
	$INSTDIR/usr/bin/patch -N --dry-run /usr/palm/applications/com.palm.app.messaging/resources/it_it/views/prefsAccountSummary/prefsAccountSummary-scene.html < $INSTDIR/usr/palm/applications/org.webosinternals.messaging/Patches/$WEBOSVER/it_it_prefsAccountSummary-scene.patch || CheckPatch it_it_prefsAccountSummary-scene >> $PATCH_LOG
fi

#Patch messaging application
$INSTDIR/usr/bin/patch -N /usr/palm/applications/com.palm.app.messaging/app/models/messaging-constants.js < $INSTDIR/usr/palm/applications/org.webosinternals.messaging/Patches/$WEBOSVER/messaging-constants.patch || PatchFailed messaging-constants >> $PATCH_LOG
if (grep  -i "isNumberValid" /usr/palm/applications/com.palm.app.messaging/app/models/messaging-luna-service.js) ; then
	$INSTDIR/usr/bin/patch -N /usr/palm/applications/com.palm.app.messaging/app/models/messaging-luna-service.js < $INSTDIR/usr/palm/applications/org.webosinternals.messaging/Patches/$WEBOSVER/messaging-luna-service.smstonepatch || CheckPatch messaging-luna-service >> $PATCH_LOG
	$INSTDIR/usr/bin/patch -N /usr/palm/applications/com.palm.app.messaging/app/controllers/listview-assistant.js < $INSTDIR/usr/palm/applications/org.webosinternals.messaging/Patches/$WEBOSVER/listview-assistant.smstonepatch || CheckPatch listview-assistant >> $PATCH_LOG
else
	$INSTDIR/usr/bin/patch -N /usr/palm/applications/com.palm.app.messaging/app/models/messaging-luna-service.js < $INSTDIR/usr/palm/applications/org.webosinternals.messaging/Patches/$WEBOSVER/messaging-luna-service.patch || CheckPatch messaging-luna-service >> $PATCH_LOG
	$INSTDIR/usr/bin/patch -N /usr/palm/applications/com.palm.app.messaging/app/controllers/listview-assistant.js < $INSTDIR/usr/palm/applications/org.webosinternals.messaging/Patches/$WEBOSVER/listview-assistant.patch || CheckPatch listview-assistant >> $PATCH_LOG
fi

if (grep  -i "pv_notification_repeat_interval_value" /usr/palm/applications/com.palm.app.messaging/app/views/prefsAccountSummary/prefsAccountSummary-scene.html) ; then
	$INSTDIR/usr/bin/patch -N /usr/palm/applications/com.palm.app.messaging/app/views/prefsAccountSummary/prefsAccountSummary-scene.html < $INSTDIR/usr/palm/applications/org.webosinternals.messaging/Patches/$WEBOSVER/prefsAccountSummary-scene.repeatpatch || CheckPatch prefsAccountSummary-scene >> $PATCH_LOG
	$INSTDIR/usr/bin/patch -N /usr/palm/applications/com.palm.app.messaging/app/controllers/prefsAccountSummary-assistant.js < $INSTDIR/usr/palm/applications/org.webosinternals.messaging/Patches/$WEBOSVER/prefsAccountSummary-assistant.repeatpatch || CheckPatch prefsAccountSummary-assistant >> $PATCH_LOG
else
	$INSTDIR/usr/bin/patch -N /usr/palm/applications/com.palm.app.messaging/app/views/prefsAccountSummary/prefsAccountSummary-scene.html < $INSTDIR/usr/palm/applications/org.webosinternals.messaging/Patches/$WEBOSVER/prefsAccountSummary-scene.patch || CheckPatch prefsAccountSummary-scene >> $PATCH_LOG
	$INSTDIR/usr/bin/patch -N /usr/palm/applications/com.palm.app.messaging/app/controllers/prefsAccountSummary-assistant.js < $INSTDIR/usr/palm/applications/org.webosinternals.messaging/Patches/$WEBOSVER/prefsAccountSummary-assistant.patch || CheckPatch prefsAccountSummary-assistant >> $PATCH_LOG
fi

if (grep  -i "enterSubmits: false" /usr/palm/applications/com.palm.app.messaging/app/controllers/compose-assistant.js) ; then
	$INSTDIR/usr/bin/patch -N /usr/palm/applications/com.palm.app.messaging/app/controllers/compose-assistant.js < $INSTDIR/usr/palm/applications/org.webosinternals.messaging/Patches/$WEBOSVER/compose-assistant.enterpatch || CheckPatch compose-assistant >> $PATCH_LOG
else
	$INSTDIR/usr/bin/patch -N /usr/palm/applications/com.palm.app.messaging/app/controllers/compose-assistant.js < $INSTDIR/usr/palm/applications/org.webosinternals.messaging/Patches/$WEBOSVER/compose-assistant.patch || CheckPatch compose-assistant >> $PATCH_LOG
fi

$INSTDIR/usr/bin/patch -N /usr/palm/applications/com.palm.app.messaging/app/views/prefsSetupAccount/prefsSetupAccount-scene.html < $INSTDIR/usr/palm/applications/org.webosinternals.messaging/Patches/$WEBOSVER/prefsSetupAccount-scene.patch || PatchFailed prefsSetupAccount-scene >> $PATCH_LOG
$INSTDIR/usr/bin/patch -N /usr/palm/applications/com.palm.app.messaging/app/controllers/prefsAccountTypeList-assistant.js < $INSTDIR/usr/palm/applications/org.webosinternals.messaging/Patches/$WEBOSVER/prefsAccountTypeList-assistant.patch || PatchFailed prefsAccountTypeList-assistant >> $PATCH_LOG
$INSTDIR/usr/bin/patch -N /usr/palm/applications/com.palm.app.messaging/app/controllers/prefsSetupAccount-assistant.js < $INSTDIR/usr/palm/applications/org.webosinternals.messaging/Patches/$WEBOSVER/prefsSetupAccount-assistant.patch || PatchFailed prefsSetupAccount-assistant >> $PATCH_LOG
$INSTDIR/usr/bin/patch -N /usr/palm/applications/com.palm.app.messaging/stylesheets/messaging.css < $INSTDIR/usr/palm/applications/org.webosinternals.messaging/Patches/$WEBOSVER/messaging.patch || PatchFailed messaging >> $PATCH_LOG
$INSTDIR/usr/bin/patch -N /usr/palm/frameworks/mojo/submissions/$SUBVER/stylesheets/global-iconography.css < $INSTDIR/usr/palm/applications/org.webosinternals.messaging/Patches/$WEBOSVER/global-iconography.patch || PatchFailed global-iconography >> $PATCH_LOG
$INSTDIR/usr/bin/patch -N /usr/palm/frameworks/mojo/submissions/$SUBVER/stylesheets/global-widget-addressing.css < $INSTDIR/usr/palm/applications/org.webosinternals.messaging/Patches/$WEBOSVER/global-widget-addressing.patch || PatchFailed global-widget-addressing >> $PATCH_LOG
$INSTDIR/usr/bin/patch -N /usr/palm/applications/com.palm.app.messaging/app/views/prefsAccountSummary/accountsRow.html < $INSTDIR/usr/palm/applications/org.webosinternals.messaging/Patches/$WEBOSVER/accountsRow.patch || PatchFailed accountsRow >> $PATCH_LOG

#Patch Contacts Application
$INSTDIR/usr/bin/patch -N /usr/palm/applications/com.palm.app.contacts/app/models/edit-rules.js < $INSTDIR/usr/palm/applications/org.webosinternals.messaging/Patches/$WEBOSVER/edit-rules.patch || PatchFailed edit-rules >> $PATCH_LOG
$INSTDIR/usr/bin/patch -N /usr/palm/applications/com.palm.app.contacts/app/models/im-model.js < $INSTDIR/usr/palm/applications/org.webosinternals.messaging/Patches/$WEBOSVER/im-model.patch || PatchFailed im-model >> $PATCH_LOG

if [ -f /usr/palm/applications/com.palm.app.messaging/resources/de_de/views/prefsSetupAccount/prefsSetupAccount-scene.html ]; then
	#Other languages
	$INSTDIR/usr/bin/patch -N /usr/palm/applications/com.palm.app.messaging/resources/de_de/views/prefsSetupAccount/prefsSetupAccount-scene.html < $INSTDIR/usr/palm/applications/org.webosinternals.messaging/Patches/$WEBOSVER/de_de_prefsSetupAccount-scene.patch || PatchFailed de_de_prefsSetupAccount-scene >> $PATCH_LOG
	$INSTDIR/usr/bin/patch -N /usr/palm/applications/com.palm.app.messaging/resources/es_es/views/prefsSetupAccount/prefsSetupAccount-scene.html < $INSTDIR/usr/palm/applications/org.webosinternals.messaging/Patches/$WEBOSVER/es_es_prefsSetupAccount-scene.patch || PatchFailed es_es_prefsSetupAccount-scene >> $PATCH_LOG
	$INSTDIR/usr/bin/patch -N /usr/palm/applications/com.palm.app.messaging/resources/es_us/views/prefsSetupAccount/prefsSetupAccount-scene.html < $INSTDIR/usr/palm/applications/org.webosinternals.messaging/Patches/$WEBOSVER/es_us_prefsSetupAccount-scene.patch || PatchFailed es_us_prefsSetupAccount-scene >> $PATCH_LOG
	$INSTDIR/usr/bin/patch -N /usr/palm/applications/com.palm.app.messaging/resources/fr_ca/views/prefsSetupAccount/prefsSetupAccount-scene.html < $INSTDIR/usr/palm/applications/org.webosinternals.messaging/Patches/$WEBOSVER/fr_ca_prefsSetupAccount-scene.patch || PatchFailed fr_ca_prefsSetupAccount-scene >> $PATCH_LOG
	$INSTDIR/usr/bin/patch -N /usr/palm/applications/com.palm.app.messaging/resources/fr_fr/views/prefsSetupAccount/prefsSetupAccount-scene.html < $INSTDIR/usr/palm/applications/org.webosinternals.messaging/Patches/$WEBOSVER/fr_fr_prefsSetupAccount-scene.patch || PatchFailed fr_fr_prefsSetupAccount-scene >> $PATCH_LOG
	$INSTDIR/usr/bin/patch -N /usr/palm/applications/com.palm.app.messaging/resources/it_it/views/prefsSetupAccount/prefsSetupAccount-scene.html < $INSTDIR/usr/palm/applications/org.webosinternals.messaging/Patches/$WEBOSVER/it_it_prefsSetupAccount-scene.patch || PatchFailed it_it_prefsSetupAccount-scene >> $PATCH_LOG
fi

if [ -f /usr/palm/applications/com.palm.app.messaging/resources/de_de/views/prefsAccountSummary/prefsAccountSummary-scene.html ]; then
	#Other languages
	$INSTDIR/usr/bin/patch -N /usr/palm/applications/com.palm.app.messaging/resources/de_de/views/prefsAccountSummary/prefsAccountSummary-scene.html < $INSTDIR/usr/palm/applications/org.webosinternals.messaging/Patches/$WEBOSVER/de_de_prefsAccountSummary-scene.patch || PatchFailed de_de_prefsAccountSummary-scene >> $PATCH_LOG
	$INSTDIR/usr/bin/patch -N /usr/palm/applications/com.palm.app.messaging/resources/es_es/views/prefsAccountSummary/prefsAccountSummary-scene.html < $INSTDIR/usr/palm/applications/org.webosinternals.messaging/Patches/$WEBOSVER/es_es_prefsAccountSummary-scene.patch || PatchFailed es_es_prefsAccountSummary-scene >> $PATCH_LOG
	$INSTDIR/usr/bin/patch -N /usr/palm/applications/com.palm.app.messaging/resources/es_us/views/prefsAccountSummary/prefsAccountSummary-scene.html < $INSTDIR/usr/palm/applications/org.webosinternals.messaging/Patches/$WEBOSVER/es_us_prefsAccountSummary-scene.patch || PatchFailed es_us_prefsAccountSummary-scene >> $PATCH_LOG
	$INSTDIR/usr/bin/patch -N /usr/palm/applications/com.palm.app.messaging/resources/fr_ca/views/prefsAccountSummary/prefsAccountSummary-scene.html < $INSTDIR/usr/palm/applications/org.webosinternals.messaging/Patches/$WEBOSVER/fr_ca_prefsAccountSummary-scene.patch || PatchFailed fr_ca_prefsAccountSummary-scene >> $PATCH_LOG
	$INSTDIR/usr/bin/patch -N /usr/palm/applications/com.palm.app.messaging/resources/fr_fr/views/prefsAccountSummary/prefsAccountSummary-scene.html < $INSTDIR/usr/palm/applications/org.webosinternals.messaging/Patches/$WEBOSVER/fr_fr_prefsAccountSummary-scene.patch || PatchFailed fr_fr_prefsAccountSummary-scene >> $PATCH_LOG
	$INSTDIR/usr/bin/patch -N /usr/palm/applications/com.palm.app.messaging/resources/it_it/views/prefsAccountSummary/prefsAccountSummary-scene.html < $INSTDIR/usr/palm/applications/org.webosinternals.messaging/Patches/$WEBOSVER/it_it_prefsAccountSummary-scene.patch || PatchFailed it_it_prefsAccountSummary-scene >> $PATCH_LOG
fi

#Kill LibpurpleAdapterExt if it's running
kill `ps -ef | grep LibpurpleAdapterExt | grep -v grep | awk '{print $2}'` 
kill `ps -ef | grep LibpurpleAdapterExt | grep -v grep | awk '{print $2}'`
kill `ps -ef | grep LibpurpleAdapterExt | grep -v grep | awk '{print $2}'`
#Kill LibpurpleAdapter if it's running
kill `ps -ef | grep LibpurpleAdapter | grep -v grep | awk '{print $2}'`
kill `ps -ef | grep LibpurpleAdapter | grep -v grep | awk '{print $2}'`
kill `ps -ef | grep LibpurpleAdapter | grep -v grep | awk '{print $2}'`

#Backup Files (only if they don't exist already)
if [ ! -f $INSTDIR/luna/data/dbdata/PalmDatabase.db3.messback ]; then
	cp $INSTDIR/luna/data/dbdata/PalmDatabase.db3 $INSTDIR/luna/data/dbdata/PalmDatabase.db3.messback
fi

#Backup Palm Libraries
if [ ! -d /usr/lib/purple-2.messback ]; then
	cp /usr/lib/purple-2 /usr/lib/purple-2.messback -r
fi
if [ ! -d /usr/share/purple/ca-certs.messback ]; then
	cp /usr/share/purple/ca-certs /usr/share/purple/ca-certs.messback -r
fi

#Copy Service File
ln -s $INSTDIR/usr/palm/applications/org.webosinternals.messaging/usr/share/dbus-1/system-services/im.libpurpleext.greg.service /usr/share/dbus-1/system-services/im.libpurpleext.greg.service

#Cleanup Patching Failures
rm /usr/palm/applications/com.palm.app.messaging/app/models/*.rej
rm /usr/palm/applications/com.palm.app.messaging/app/controllers/*.rej
rm /usr/palm/frameworks/mojo/submissions/$SUBVER/stylesheets/*.rej

#Update Database (call Java)
sh $INSTDIR/usr/palm/applications/org.webosinternals.messaging/MessagingPlugins.sh $INSTDIR InstallPlugin Palm

#Copy files for installation
rm -f -r /usr/lib/purple-2/
ln -s $INSTDIR/usr/palm/applications/org.webosinternals.messaging/usr/lib/purple-2/ /usr/lib/purple-2
rm -f -r /usr/share/purple/ca-certs
ln -s $INSTDIR/usr/palm/applications/org.webosinternals.messaging/usr/share/purple/ca-certs/ /usr/share/purple/ca-certs
cp $INSTDIR/usr/palm/applications/org.webosinternals.messaging/usr/palm/applications/com.palm.app.messaging/images/transports/* /usr/palm/applications/com.palm.app.messaging/images/transports/
cp $INSTDIR/usr/palm/applications/org.webosinternals.messaging/usr/palm/applications/com.palm.app.messaging/images/menu-icon-refresh.png /usr/palm/applications/com.palm.app.messaging/images/menu-icon-refresh.png
cp $INSTDIR/usr/palm/applications/org.webosinternals.messaging/usr/palm/frameworks/mojo/submissions/X.X/images/accounts/* /usr/palm/frameworks/mojo/submissions/$SUBVER/images/accounts/
cp $INSTDIR/usr/palm/applications/org.webosinternals.messaging/usr/palm/applications/com.palm.app.messaging/app/views/prefsSetupAccount/* /usr/palm/applications/com.palm.app.messaging/app/views/prefsSetupAccount/
cp $INSTDIR/usr/palm/applications/org.webosinternals.messaging/usr/palm/applications/com.palm.app.messaging/app/views/prefsAccountSummary/* /usr/palm/applications/com.palm.app.messaging/app/views/prefsAccountSummary/

#Install LibpurpleAdapterExt (Create symlink)
rm -f /usr/bin/LibpurpleAdapterExt
cp $INSTDIR/usr/palm/applications/org.webosinternals.messaging/usr/bin/LibpurpleAdapterExt /usr/bin/LibpurpleAdapterExt

#Create sym links for Yahoo
rm -f /usr/lib/libymsg.so.0
ln -s $INSTDIR/usr/palm/applications/org.webosinternals.messagingsysfiles/usr/lib/libymsg.so.0.0.0 /usr/lib/libymsg.so.0

#Create sym links for ICQ and Aim Plugin
rm -f /usr/lib/liboscar.so
rm -f /usr/lib/liboscar.so.0
ln -s $INSTDIR/usr/palm/applications/org.webosinternals.messaging/usr/lib/purple-2/liboscar.so.0.0.0 /usr/lib/liboscar.so
ln -s $INSTDIR/usr/palm/applications/org.webosinternals.messaging/usr/lib/purple-2/liboscar.so.0.0.0 /usr/lib/liboscar.so.0

#Create sym links for Jabber
rm -f /usr/lib/libjabber.so
rm -f /usr/lib/libjabber.so.0
ln -s $INSTDIR/usr/palm/applications/org.webosinternals.messaging/usr/lib/purple-2/libjabber.so.0.0.0 /usr/lib/libjabber.so
ln -s $INSTDIR/usr/palm/applications/org.webosinternals.messaging/usr/lib/purple-2/libjabber.so.0.0.0 /usr/lib/libjabber.so.0

#Chmod LibPurpleAdapterExt and MessagingPlugins.sh
chmod 755 /usr/bin/LibpurpleAdapterExt
chmod 755 $INSTDIR/usr/palm/applications/org.webosinternals.messaging/MessagingPlugins.sh
chmod 755 $INSTDIR/usr/palm/applications/org.webosinternals.messaging/DebugMP.sh
ln -s $INSTDIR/usr/palm/applications/org.webosinternals.messaging/DebugMP.sh /var/home/root/DebugMP.sh

#Create /var/preferences/org.webosinternals.messaging/ directory if required
if [ ! -d /var/preferences/org.webosinternals.messaging/ ]; then
	mkdir /var/preferences/org.webosinternals.messaging/
fi

#Cleanup
rm -f /var/tmp/webosver

#Reinstall Plugins if available
#All Plugins
if [ -f $INSTDIR/usr/lib/ipkg/info/org.webosinternals.messagingallplugins.postinst ]; then
	sh $INSTDIR/usr/lib/ipkg/info/org.webosinternals.messagingallplugins.postinst
fi
#Groupwise
if [ -f $INSTDIR/usr/lib/ipkg/info/org.webosinternals.messaginggroupwise.postinst ]; then
	sh $INSTDIR/usr/lib/ipkg/info/org.webosinternals.messaginggroupwise.postinst
fi
#ICQ
if [ -f $INSTDIR/usr/lib/ipkg/info/org.webosinternals.messagingicq.postinst ]; then
	sh $INSTDIR/usr/lib/ipkg/info/org.webosinternals.messagingicq.postinst
fi
#IRC
if [ -f $INSTDIR/usr/lib/ipkg/info/org.webosinternals.messagingirc.postinst ]; then
	sh $INSTDIR/usr/lib/ipkg/info/org.webosinternals.messagingirc.postinst
fi
#Jabber
if [ -f $INSTDIR/usr/lib/ipkg/info/org.webosinternals.messagingjabber.postinst ]; then
	sh $INSTDIR/usr/lib/ipkg/info/org.webosinternals.messagingjabber.postinst
fi
#Live
if [ -f $INSTDIR/usr/lib/ipkg/info/org.webosinternals.messaginglive.postinst ]; then
	sh $INSTDIR/usr/lib/ipkg/info/org.webosinternals.messaginglive.postinst
fi
#Office Communicator
if [ -f $INSTDIR/usr/lib/ipkg/info/org.webosinternals.messagingofficecommunicator.postinst ]; then
	sh $INSTDIR/usr/lib/ipkg/info/org.webosinternals.messagingofficecommunicator.postinst
fi
#QQ
if [ -f $INSTDIR/usr/lib/ipkg/info/org.webosinternals.messagingqq.postinst ]; then
	sh $INSTDIR/usr/lib/ipkg/info/org.webosinternals.messagingqq.postinst
fi
#Sametime
if [ -f $INSTDIR/usr/lib/ipkg/info/org.webosinternals.messagingsametime.postinst ]; then
	sh $INSTDIR/usr/lib/ipkg/info/org.webosinternals.messagingsametime.postinst
fi
#xfire
if [ -f $INSTDIR/usr/lib/ipkg/info/org.webosinternals.messagingxfire.postinst ]; then
	sh $INSTDIR/usr/lib/ipkg/info/org.webosinternals.messagingxfire.postinst
fi
#facebook
if [ -f $INSTDIR/usr/lib/ipkg/info/org.webosinternals.messagingfacebook.postinst ]; then
	sh $INSTDIR/usr/lib/ipkg/info/org.webosinternals.messagingfacebook.postinst
fi
#gadu
if [ -f $INSTDIR/usr/lib/ipkg/info/org.webosinternals.messaginggadu.postinst ]; then
	sh $INSTDIR/usr/lib/ipkg/info/org.webosinternals.messaginggadu.postinst
fi
#myspace
if [ -f $INSTDIR/usr/lib/ipkg/info/org.webosinternals.messagingmyspace.postinst ]; then
	sh $INSTDIR/usr/lib/ipkg/info/org.webosinternals.messagingmyspace.postinst
fi

echo "" >> $PATCH_LOG
echo "----------------------------------" >> $PATCH_LOG
echo "COMPLETE!" >> $PATCH_LOG

exit 0